# Generated by Django 5.2.1 on 2025-05-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Dispositivo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
            },
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Marca de Tiempo"
                    ),
                ),
                (
                    "prefijo_id_rt",
                    models.CharField(
                        blank=True,
                        help_text="Prefijo identificador del receptor/sensor para seleccionar la fórmula de conversión.",
                        max_length=20,
                        null=True,
                        verbose_name="Prefijo ID Receptor",
                    ),
                ),
                (
                    "valor_crudo_psi",
                    models.FloatField(
                        blank=True,
                        help_text="Valor crudo de presión en PSI (libras por pulgada cuadrada).",
                        null=True,
                        verbose_name="Valor Crudo Presión (PSI)",
                    ),
                ),
                (
                    "valor_crudo_temp",
                    models.FloatField(
                        blank=True,
                        help_text="Valor crudo de temperatura (unidad original del sensor).",
                        null=True,
                        verbose_name="Valor Crudo Temperatura",
                    ),
                ),
                (
                    "valor_crudo_volt",
                    models.FloatField(
                        blank=True,
                        help_text="Valor crudo de voltaje.",
                        null=True,
                        verbose_name="Valor Crudo Voltaje",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitud"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitud"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="Altitud"),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, null=True, verbose_name="Velocidad"),
                ),
                (
                    "course",
                    models.FloatField(blank=True, null=True, verbose_name="Curso"),
                ),
                (
                    "satellites",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Satélites"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="core_app.device",
                        verbose_name="Dispositivo Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato",
                "verbose_name_plural": "Datos",
                "ordering": ["-timestamp"],
            },
        ),
    ]
