# Generated by Django 5.2.1 on 2025-05-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial_setup'),
    ]

    operations = [
    ]
